### ISSUE TITLE
Sass::SyntaxError in Spree/admin/orders#index

### ISSUE THREAD

**Issue by rocknrollMarc** [AlchemyCMS/alchemy-spree-demo#3]
Sass::SyntaxError in Spree/admin/orders#index

Showing /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/bundler/gems/spree-55a4b0d162a6/backend/app/views/spree/admin/shared/_head.html.erb where line #13 raised:

File to import not found or unreadable: globals/functions.
Load paths:
  Sass::Rails::Importer(/Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/bundler/gems/spree-55a4b0d162a6/backend/app/assets/stylesheets/admin/spree_admin.scss)
  /Users/marc/workspace/rails/spree_ecomerce/alchemy-spree-demo/app/assets/stylesheets
  /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/compass-0.12.2/frameworks/blueprint/stylesheets
  /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/compass-0.12.2/frameworks/compass/stylesheets
  /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/sassy-buttons-0.1.4/stylesheets
  /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/gems/zurb-foundation-4.3.2/scss
  Compass::SpriteImporter
  (in /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/bundler/gems/spree-55a4b0d162a6/backend/app/assets/stylesheets/admin/spree_admin.scss)
Extracted source (around line #13):

10: 
11: <link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600&subset=latin,cyrillic,greek,vietnamese' rel='stylesheet' type='text/css'>
12: 
13: <%= stylesheet_link_tag 'admin/all' %>
14: 
15: <%= javascript_include_tag 'admin/all' %>
16: 
Trace of template inclusion: /Users/marc/.rvm/gems/ruby-1.9.3-p551@spree_alchemy_rails_3.2.15/bundler/gems/spree-55a4b0d162a6/backend/app/views/spree/layouts/admin.html.erb

Rails.root: /Users/marc/workspace/rails/spree_ecomerce/alchemy-spree-demo

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"q"=>{"completed_at_not_null"=>"1",
 "s"=>"completed_at desc",
 "created_at_gt"=>nil,
 "created_at_lt"=>nil}}
Show session dump

Show env dump

Response

Headers:

None

**Comment by rocknrollMarc** [comment]
happens when I try to open the spree view in alchemy admin pannel

**Comment by tvdeyen** [comment]
We don't support this gem anymore as we use Solidus instead. 

https://github.com/AlchemyCMS/alchemy-solidus

**Comment by rocknrollMarc** [comment]
Oh hihihi. Alles klar kuck ich mir mal an vielleicht ist das ja auch was für uns, haben uns noch nicht auf eine E-commerce Plattform festgelegt. Danke für die info.

:)
