### ISSUE TITLE
Gem Load Error is: uninitialized constant Mysql2::Client::SECURE_CONNECTION

### ISSUE THREAD

**Issue by rocknrollMarc** [AlchemyCMS/alchemy-spree-demo#5]
Fixed by adding

config/initializers/abstract_mysql_adapter.rb

class ActiveRecord::ConnectionAdapters::Mysql2Adapter
NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end

**Comment by tvdeyen** [comment]
This gem/demo is abondonned. Please use alchemy-solidus integration instead
